### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by merval** [wknowleskellett/FactoryBlock#1]
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Factory Block' (factory_block) 1.0.0 with any version that is compatible with:
		 - minecraft 1.21
More details:
	 - Mod 'Factory Block' (factory_block) 1.0.0 requires any version between 1.19.4 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by wknowleskellett** [comment]
Hi @merval ! I haven't updated my mods since 1.19.4 but I'd be happy to. I'm moving apartments right now but I can do it sometime in the next week or two.
I'd love to know your experience playing with it! I haven't heard from anyone who's tried it. Let me know in the comments of the demo video.
